import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDate } from "../utils/formatUtils";
import { getStatusColor, capitalizeWords, cleanStr } from "../utils/getStatusColor";


const ChallanTableView = ({ challans = [], vehicleNo }) => {
  // Generate PDF for each challan
  const downloadChallanPDF = (challan) => {
    const doc = new jsPDF("p", "mm", "a4");

    // Optional: Add logo
    const img = new Image();
    img.src = "/challan.png";

    // Header
    doc.setFont("helvetica", "normal");
    doc.setFontSize(18);
    doc.text("E-Challan Report", 14, 20);

    const vNo = vehicleNo?.trim() || "N/A";
    doc.setFontSize(16);
    doc.text(`Vehicle No: ${vNo}`, 14, 30);
    doc.text(`Amount: ${challan.amountDisplay}`, 14, 40);

    // Table
    autoTable(doc, {
      startY: 50,
      head: [["Field", "Details"]],
      body: [
        ["Challan Number", challan.challanNumber],
        ["Accused Name", challan.accusedName],
        ["Father Name", challan.accused_father_name],
        ["Offense", challan.offenseDetails],
        ["Place", challan.challanPlace || "N/A"],
        ["Date", challan.challanDate],
        ["Status", challan.status],
        ["Court", challan.court || "N/A"],
        ["State", challan.state || "N/A"],
        ["RTO", challan.rto || "N/A"],
      ],
      theme: "grid",
      styles: { fontSize: 11 },
      headStyles: { fillColor: [41, 128, 185] },
    });

    doc.setFontSize(10);
    doc.text(
      "Generated by Challan Expert Website",
      14,
      doc.internal.pageSize.height - 10
    );

    doc.save(`Challan_${challan.challanNumber}.pdf`);
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200">
      {challans.length > 0 ? (
        <div className="overflow-x-auto">
          <table className="w-full table-auto border-collapse">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Serial No.
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Challan Details
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Offense
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Date & Time
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Amount
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Status
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Court
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  State
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  RTO
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Image
                </th>
                <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase">
                  Download PDF
                </th>
              </tr>
            </thead>

            <tbody className="bg-white divide-y divide-gray-200">
              {challans.map((challan, i) => (
                <tr key={i} className="hover:bg-gray-50">
                  <td className="px-3 py-2 text-xs font-medium">{i + 1}</td>
                  <td className="px-3 py-2">
                    <div>
                      <div className="text-xs font-medium text-gray-900">
                        {challan.challanNumber}
                      </div>
                      <div className="text-xs text-gray-500">
                        {challan.accusedName}
                      </div>
                    </div>
                  </td>
                  <td className="px-3 py-2 text-xs text-gray-900 max-w-xs">
                    {challan.offenseDetails}
                    {challan.challanPlace && (
                      <div className="text-gray-500 mt-1 text-xs">
                        📍 {challan.challanPlace}
                      </div>
                    )}
                  </td>
                  <td className="px-3 py-2 text-xs text-gray-900">
                    {formatDate(challan.challanDate)}
                  </td>
                  <td className="px-3 py-2 text-xs font-semibold text-gray-900">
                    {challan.amountDisplay}
                  </td>
                  <td className="px-3 py-2">
                    <span
                      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(
                        challan.status
                      )}`}
                    >
                      {challan.status}
                    </span>
                  </td>
                  <td className="px-3 py-2 text-xs">{challan.court}</td>
                  <td className="px-3 py-2 text-xs">
                    {challan.state || "N/A"}
                  </td>
                  <td className="px-3 py-2 text-xs">{challan.rto || "N/A"}</td>
                  <td className="px-3 py-2 text-xs">
                    {challan.image_url ? (
                      <img
                        src={challan.image_url}
                        alt="Challan"
                        onClick={() =>
                          window.open(challan.image_url, "_blank")
                        }
                        className="w-16 h-16 object-cover rounded cursor-pointer hover:opacity-80 transition"
                      />
                    ) : (
                      <span className="text-gray-500 italic">--</span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-xs">
                    <button
                      onClick={() => downloadChallanPDF(challan)}
                      className="px-3 py-1 bg-green-600 text-white rounded-lg hover:bg-green-700"
                    >
                      Download PDF
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="p-12 text-center text-gray-500">
          <div className="mb-4">🚗</div>
          <h3 className="text-lg font-medium mb-2">No Challan Records</h3>
          <p>Search for a vehicle number to view challan records.</p>
        </div>
      )}
    </div>
  );
};

export default ChallanTableView;
